import React from 'react';
import { motion } from 'framer-motion';

const Hero = ({ onPrimary, onSecondary }) => {
  return (
    <section className="flex flex-col-reverse lg:flex-row items-center justify-between py-20 px-8" id="hero">
      {/* text */}
      <motion.div
        className="max-w-xl text-center lg:text-left"
        initial={{ opacity: 0, x: -50 }}
        animate={{ opacity: 1, x: 0 }}
        transition={{ duration: 0.6 }}
      >
        <h1 className="text-5xl md:text-6xl font-extrabold leading-tight text-slate-900">
          Optimize your resume with{' '}
          <span className="bg-gradient-to-r from-purple-600 to-blue-500 bg-clip-text text-transparent">
            AI precision
          </span>
        </h1>
        <p className="mt-6 text-lg text-slate-700">
          Beat the bots and get in front of hiring managers using insights generated by our AI-driven ATS scanner.
        </p>
        <div className="mt-8 flex flex-col sm:flex-row gap-4 justify-center lg:justify-start">
          <button
            onClick={onPrimary}
            className="relative inline-block px-8 py-3 rounded-full bg-gradient-to-r from-purple-600 to-blue-500 text-white font-semibold shadow-xl hover:scale-105 transform transition-all"
          >
            🚀 Scan your resume
            <span className="absolute inset-0 rounded-full animate-pulse opacity-0 hover:opacity-20 bg-white"></span>
          </button>
          <button
            onClick={onSecondary}
            className="px-8 py-3 rounded-full border-2 border-purple-600 text-purple-600 font-semibold hover:bg-purple-50 transition"
          >
            ▶️ Watch Demo
          </button>
        </div>
      </motion.div>
      {/* visual placeholder */}
      <motion.div
        className="mb-12 lg:mb-0"
        initial={{ opacity: 0, x: 50 }}
        animate={{ opacity: 1, x: 0 }}
        transition={{ duration: 0.6 }}
      >
        {/* placeholder box for dashboard preview or SVG */}
        <div className="w-80 h-56 bg-gradient-to-tr from-purple-100 to-blue-100 rounded-2xl shadow-2xl flex items-center justify-center">
          <span className="text-purple-300">[Dashboard Preview]</span>
        </div>
      </motion.div>
    </section>
  );
};

export default Hero;
